<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUaXbGw8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUaXbGw8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUaXbGw8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUaXbGw8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUaXbGw8\App_KernelDevDebugContainer([
    'container.build_hash' => 'UaXbGw8',
    'container.build_id' => '6c671c96',
    'container.build_time' => 1632482311,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUaXbGw8');
