<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCqMWuhf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCqMWuhf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCqMWuhf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCqMWuhf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCqMWuhf\App_KernelDevDebugContainer([
    'container.build_hash' => 'CqMWuhf',
    'container.build_id' => '8f893252',
    'container.build_time' => 1633422737,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCqMWuhf');
